language: python
python: 
- "3.7.4"
install:  
- pip install -e .
# Install packages for code coverage report
- pip install pytest-cov codecov    
- pip install -r requirements.txt
script:  
# Point to the source directory
- pytest --cov=oanda_v20_platform tests
after_success:  
# uploads report to codecov.io
- codecov                           
